// Static country list generated from https://flagcdn.com/en/codes.json (ISO 3166-1 alpha-2)
// Replaces the deprecated restcountries.com v3.1 API. Flag images served by flagcdn.com,
// the same CDN the old API linked to.
export interface Country {
  name: { common: string }
  cca2: string
  flags: { svg: string; png: string }
}

export const COUNTRIES: Country[] = [
  { name: { common: "Afghanistan" }, cca2: 'AF', flags: { svg: 'https://flagcdn.com/af.svg', png: 'https://flagcdn.com/w40/af.png' } },
  { name: { common: "Åland Islands" }, cca2: 'AX', flags: { svg: 'https://flagcdn.com/ax.svg', png: 'https://flagcdn.com/w40/ax.png' } },
  { name: { common: "Albania" }, cca2: 'AL', flags: { svg: 'https://flagcdn.com/al.svg', png: 'https://flagcdn.com/w40/al.png' } },
  { name: { common: "Algeria" }, cca2: 'DZ', flags: { svg: 'https://flagcdn.com/dz.svg', png: 'https://flagcdn.com/w40/dz.png' } },
  { name: { common: "American Samoa" }, cca2: 'AS', flags: { svg: 'https://flagcdn.com/as.svg', png: 'https://flagcdn.com/w40/as.png' } },
  { name: { common: "Andorra" }, cca2: 'AD', flags: { svg: 'https://flagcdn.com/ad.svg', png: 'https://flagcdn.com/w40/ad.png' } },
  { name: { common: "Angola" }, cca2: 'AO', flags: { svg: 'https://flagcdn.com/ao.svg', png: 'https://flagcdn.com/w40/ao.png' } },
  { name: { common: "Anguilla" }, cca2: 'AI', flags: { svg: 'https://flagcdn.com/ai.svg', png: 'https://flagcdn.com/w40/ai.png' } },
  { name: { common: "Antarctica" }, cca2: 'AQ', flags: { svg: 'https://flagcdn.com/aq.svg', png: 'https://flagcdn.com/w40/aq.png' } },
  { name: { common: "Antigua and Barbuda" }, cca2: 'AG', flags: { svg: 'https://flagcdn.com/ag.svg', png: 'https://flagcdn.com/w40/ag.png' } },
  { name: { common: "Argentina" }, cca2: 'AR', flags: { svg: 'https://flagcdn.com/ar.svg', png: 'https://flagcdn.com/w40/ar.png' } },
  { name: { common: "Armenia" }, cca2: 'AM', flags: { svg: 'https://flagcdn.com/am.svg', png: 'https://flagcdn.com/w40/am.png' } },
  { name: { common: "Aruba" }, cca2: 'AW', flags: { svg: 'https://flagcdn.com/aw.svg', png: 'https://flagcdn.com/w40/aw.png' } },
  { name: { common: "Australia" }, cca2: 'AU', flags: { svg: 'https://flagcdn.com/au.svg', png: 'https://flagcdn.com/w40/au.png' } },
  { name: { common: "Austria" }, cca2: 'AT', flags: { svg: 'https://flagcdn.com/at.svg', png: 'https://flagcdn.com/w40/at.png' } },
  { name: { common: "Azerbaijan" }, cca2: 'AZ', flags: { svg: 'https://flagcdn.com/az.svg', png: 'https://flagcdn.com/w40/az.png' } },
  { name: { common: "Bahamas" }, cca2: 'BS', flags: { svg: 'https://flagcdn.com/bs.svg', png: 'https://flagcdn.com/w40/bs.png' } },
  { name: { common: "Bahrain" }, cca2: 'BH', flags: { svg: 'https://flagcdn.com/bh.svg', png: 'https://flagcdn.com/w40/bh.png' } },
  { name: { common: "Bangladesh" }, cca2: 'BD', flags: { svg: 'https://flagcdn.com/bd.svg', png: 'https://flagcdn.com/w40/bd.png' } },
  { name: { common: "Barbados" }, cca2: 'BB', flags: { svg: 'https://flagcdn.com/bb.svg', png: 'https://flagcdn.com/w40/bb.png' } },
  { name: { common: "Belarus" }, cca2: 'BY', flags: { svg: 'https://flagcdn.com/by.svg', png: 'https://flagcdn.com/w40/by.png' } },
  { name: { common: "Belgium" }, cca2: 'BE', flags: { svg: 'https://flagcdn.com/be.svg', png: 'https://flagcdn.com/w40/be.png' } },
  { name: { common: "Belize" }, cca2: 'BZ', flags: { svg: 'https://flagcdn.com/bz.svg', png: 'https://flagcdn.com/w40/bz.png' } },
  { name: { common: "Benin" }, cca2: 'BJ', flags: { svg: 'https://flagcdn.com/bj.svg', png: 'https://flagcdn.com/w40/bj.png' } },
  { name: { common: "Bermuda" }, cca2: 'BM', flags: { svg: 'https://flagcdn.com/bm.svg', png: 'https://flagcdn.com/w40/bm.png' } },
  { name: { common: "Bhutan" }, cca2: 'BT', flags: { svg: 'https://flagcdn.com/bt.svg', png: 'https://flagcdn.com/w40/bt.png' } },
  { name: { common: "Bolivia" }, cca2: 'BO', flags: { svg: 'https://flagcdn.com/bo.svg', png: 'https://flagcdn.com/w40/bo.png' } },
  { name: { common: "Bosnia and Herzegovina" }, cca2: 'BA', flags: { svg: 'https://flagcdn.com/ba.svg', png: 'https://flagcdn.com/w40/ba.png' } },
  { name: { common: "Botswana" }, cca2: 'BW', flags: { svg: 'https://flagcdn.com/bw.svg', png: 'https://flagcdn.com/w40/bw.png' } },
  { name: { common: "Bouvet Island" }, cca2: 'BV', flags: { svg: 'https://flagcdn.com/bv.svg', png: 'https://flagcdn.com/w40/bv.png' } },
  { name: { common: "Brazil" }, cca2: 'BR', flags: { svg: 'https://flagcdn.com/br.svg', png: 'https://flagcdn.com/w40/br.png' } },
  { name: { common: "British Indian Ocean Territory" }, cca2: 'IO', flags: { svg: 'https://flagcdn.com/io.svg', png: 'https://flagcdn.com/w40/io.png' } },
  { name: { common: "British Virgin Islands" }, cca2: 'VG', flags: { svg: 'https://flagcdn.com/vg.svg', png: 'https://flagcdn.com/w40/vg.png' } },
  { name: { common: "Brunei" }, cca2: 'BN', flags: { svg: 'https://flagcdn.com/bn.svg', png: 'https://flagcdn.com/w40/bn.png' } },
  { name: { common: "Bulgaria" }, cca2: 'BG', flags: { svg: 'https://flagcdn.com/bg.svg', png: 'https://flagcdn.com/w40/bg.png' } },
  { name: { common: "Burkina Faso" }, cca2: 'BF', flags: { svg: 'https://flagcdn.com/bf.svg', png: 'https://flagcdn.com/w40/bf.png' } },
  { name: { common: "Burundi" }, cca2: 'BI', flags: { svg: 'https://flagcdn.com/bi.svg', png: 'https://flagcdn.com/w40/bi.png' } },
  { name: { common: "Cambodia" }, cca2: 'KH', flags: { svg: 'https://flagcdn.com/kh.svg', png: 'https://flagcdn.com/w40/kh.png' } },
  { name: { common: "Cameroon" }, cca2: 'CM', flags: { svg: 'https://flagcdn.com/cm.svg', png: 'https://flagcdn.com/w40/cm.png' } },
  { name: { common: "Canada" }, cca2: 'CA', flags: { svg: 'https://flagcdn.com/ca.svg', png: 'https://flagcdn.com/w40/ca.png' } },
  { name: { common: "Cape Verde" }, cca2: 'CV', flags: { svg: 'https://flagcdn.com/cv.svg', png: 'https://flagcdn.com/w40/cv.png' } },
  { name: { common: "Caribbean Netherlands" }, cca2: 'BQ', flags: { svg: 'https://flagcdn.com/bq.svg', png: 'https://flagcdn.com/w40/bq.png' } },
  { name: { common: "Cayman Islands" }, cca2: 'KY', flags: { svg: 'https://flagcdn.com/ky.svg', png: 'https://flagcdn.com/w40/ky.png' } },
  { name: { common: "Central African Republic" }, cca2: 'CF', flags: { svg: 'https://flagcdn.com/cf.svg', png: 'https://flagcdn.com/w40/cf.png' } },
  { name: { common: "Chad" }, cca2: 'TD', flags: { svg: 'https://flagcdn.com/td.svg', png: 'https://flagcdn.com/w40/td.png' } },
  { name: { common: "Chile" }, cca2: 'CL', flags: { svg: 'https://flagcdn.com/cl.svg', png: 'https://flagcdn.com/w40/cl.png' } },
  { name: { common: "China" }, cca2: 'CN', flags: { svg: 'https://flagcdn.com/cn.svg', png: 'https://flagcdn.com/w40/cn.png' } },
  { name: { common: "Christmas Island" }, cca2: 'CX', flags: { svg: 'https://flagcdn.com/cx.svg', png: 'https://flagcdn.com/w40/cx.png' } },
  { name: { common: "Cocos (Keeling) Islands" }, cca2: 'CC', flags: { svg: 'https://flagcdn.com/cc.svg', png: 'https://flagcdn.com/w40/cc.png' } },
  { name: { common: "Colombia" }, cca2: 'CO', flags: { svg: 'https://flagcdn.com/co.svg', png: 'https://flagcdn.com/w40/co.png' } },
  { name: { common: "Comoros" }, cca2: 'KM', flags: { svg: 'https://flagcdn.com/km.svg', png: 'https://flagcdn.com/w40/km.png' } },
  { name: { common: "Cook Islands" }, cca2: 'CK', flags: { svg: 'https://flagcdn.com/ck.svg', png: 'https://flagcdn.com/w40/ck.png' } },
  { name: { common: "Costa Rica" }, cca2: 'CR', flags: { svg: 'https://flagcdn.com/cr.svg', png: 'https://flagcdn.com/w40/cr.png' } },
  { name: { common: "Côte d'Ivoire (Ivory Coast)" }, cca2: 'CI', flags: { svg: 'https://flagcdn.com/ci.svg', png: 'https://flagcdn.com/w40/ci.png' } },
  { name: { common: "Croatia" }, cca2: 'HR', flags: { svg: 'https://flagcdn.com/hr.svg', png: 'https://flagcdn.com/w40/hr.png' } },
  { name: { common: "Cuba" }, cca2: 'CU', flags: { svg: 'https://flagcdn.com/cu.svg', png: 'https://flagcdn.com/w40/cu.png' } },
  { name: { common: "Curaçao" }, cca2: 'CW', flags: { svg: 'https://flagcdn.com/cw.svg', png: 'https://flagcdn.com/w40/cw.png' } },
  { name: { common: "Cyprus" }, cca2: 'CY', flags: { svg: 'https://flagcdn.com/cy.svg', png: 'https://flagcdn.com/w40/cy.png' } },
  { name: { common: "Czechia" }, cca2: 'CZ', flags: { svg: 'https://flagcdn.com/cz.svg', png: 'https://flagcdn.com/w40/cz.png' } },
  { name: { common: "Denmark" }, cca2: 'DK', flags: { svg: 'https://flagcdn.com/dk.svg', png: 'https://flagcdn.com/w40/dk.png' } },
  { name: { common: "Djibouti" }, cca2: 'DJ', flags: { svg: 'https://flagcdn.com/dj.svg', png: 'https://flagcdn.com/w40/dj.png' } },
  { name: { common: "Dominica" }, cca2: 'DM', flags: { svg: 'https://flagcdn.com/dm.svg', png: 'https://flagcdn.com/w40/dm.png' } },
  { name: { common: "Dominican Republic" }, cca2: 'DO', flags: { svg: 'https://flagcdn.com/do.svg', png: 'https://flagcdn.com/w40/do.png' } },
  { name: { common: "DR Congo" }, cca2: 'CD', flags: { svg: 'https://flagcdn.com/cd.svg', png: 'https://flagcdn.com/w40/cd.png' } },
  { name: { common: "Ecuador" }, cca2: 'EC', flags: { svg: 'https://flagcdn.com/ec.svg', png: 'https://flagcdn.com/w40/ec.png' } },
  { name: { common: "Egypt" }, cca2: 'EG', flags: { svg: 'https://flagcdn.com/eg.svg', png: 'https://flagcdn.com/w40/eg.png' } },
  { name: { common: "El Salvador" }, cca2: 'SV', flags: { svg: 'https://flagcdn.com/sv.svg', png: 'https://flagcdn.com/w40/sv.png' } },
  { name: { common: "Equatorial Guinea" }, cca2: 'GQ', flags: { svg: 'https://flagcdn.com/gq.svg', png: 'https://flagcdn.com/w40/gq.png' } },
  { name: { common: "Eritrea" }, cca2: 'ER', flags: { svg: 'https://flagcdn.com/er.svg', png: 'https://flagcdn.com/w40/er.png' } },
  { name: { common: "Estonia" }, cca2: 'EE', flags: { svg: 'https://flagcdn.com/ee.svg', png: 'https://flagcdn.com/w40/ee.png' } },
  { name: { common: "Eswatini (Swaziland)" }, cca2: 'SZ', flags: { svg: 'https://flagcdn.com/sz.svg', png: 'https://flagcdn.com/w40/sz.png' } },
  { name: { common: "Ethiopia" }, cca2: 'ET', flags: { svg: 'https://flagcdn.com/et.svg', png: 'https://flagcdn.com/w40/et.png' } },
  { name: { common: "European Union" }, cca2: 'EU', flags: { svg: 'https://flagcdn.com/eu.svg', png: 'https://flagcdn.com/w40/eu.png' } },
  { name: { common: "Falkland Islands" }, cca2: 'FK', flags: { svg: 'https://flagcdn.com/fk.svg', png: 'https://flagcdn.com/w40/fk.png' } },
  { name: { common: "Faroe Islands" }, cca2: 'FO', flags: { svg: 'https://flagcdn.com/fo.svg', png: 'https://flagcdn.com/w40/fo.png' } },
  { name: { common: "Fiji" }, cca2: 'FJ', flags: { svg: 'https://flagcdn.com/fj.svg', png: 'https://flagcdn.com/w40/fj.png' } },
  { name: { common: "Finland" }, cca2: 'FI', flags: { svg: 'https://flagcdn.com/fi.svg', png: 'https://flagcdn.com/w40/fi.png' } },
  { name: { common: "France" }, cca2: 'FR', flags: { svg: 'https://flagcdn.com/fr.svg', png: 'https://flagcdn.com/w40/fr.png' } },
  { name: { common: "French Guiana" }, cca2: 'GF', flags: { svg: 'https://flagcdn.com/gf.svg', png: 'https://flagcdn.com/w40/gf.png' } },
  { name: { common: "French Polynesia" }, cca2: 'PF', flags: { svg: 'https://flagcdn.com/pf.svg', png: 'https://flagcdn.com/w40/pf.png' } },
  { name: { common: "French Southern and Antarctic Lands" }, cca2: 'TF', flags: { svg: 'https://flagcdn.com/tf.svg', png: 'https://flagcdn.com/w40/tf.png' } },
  { name: { common: "Gabon" }, cca2: 'GA', flags: { svg: 'https://flagcdn.com/ga.svg', png: 'https://flagcdn.com/w40/ga.png' } },
  { name: { common: "Gambia" }, cca2: 'GM', flags: { svg: 'https://flagcdn.com/gm.svg', png: 'https://flagcdn.com/w40/gm.png' } },
  { name: { common: "Georgia" }, cca2: 'GE', flags: { svg: 'https://flagcdn.com/ge.svg', png: 'https://flagcdn.com/w40/ge.png' } },
  { name: { common: "Germany" }, cca2: 'DE', flags: { svg: 'https://flagcdn.com/de.svg', png: 'https://flagcdn.com/w40/de.png' } },
  { name: { common: "Ghana" }, cca2: 'GH', flags: { svg: 'https://flagcdn.com/gh.svg', png: 'https://flagcdn.com/w40/gh.png' } },
  { name: { common: "Gibraltar" }, cca2: 'GI', flags: { svg: 'https://flagcdn.com/gi.svg', png: 'https://flagcdn.com/w40/gi.png' } },
  { name: { common: "Greece" }, cca2: 'GR', flags: { svg: 'https://flagcdn.com/gr.svg', png: 'https://flagcdn.com/w40/gr.png' } },
  { name: { common: "Greenland" }, cca2: 'GL', flags: { svg: 'https://flagcdn.com/gl.svg', png: 'https://flagcdn.com/w40/gl.png' } },
  { name: { common: "Grenada" }, cca2: 'GD', flags: { svg: 'https://flagcdn.com/gd.svg', png: 'https://flagcdn.com/w40/gd.png' } },
  { name: { common: "Guadeloupe" }, cca2: 'GP', flags: { svg: 'https://flagcdn.com/gp.svg', png: 'https://flagcdn.com/w40/gp.png' } },
  { name: { common: "Guam" }, cca2: 'GU', flags: { svg: 'https://flagcdn.com/gu.svg', png: 'https://flagcdn.com/w40/gu.png' } },
  { name: { common: "Guatemala" }, cca2: 'GT', flags: { svg: 'https://flagcdn.com/gt.svg', png: 'https://flagcdn.com/w40/gt.png' } },
  { name: { common: "Guernsey" }, cca2: 'GG', flags: { svg: 'https://flagcdn.com/gg.svg', png: 'https://flagcdn.com/w40/gg.png' } },
  { name: { common: "Guinea" }, cca2: 'GN', flags: { svg: 'https://flagcdn.com/gn.svg', png: 'https://flagcdn.com/w40/gn.png' } },
  { name: { common: "Guinea-Bissau" }, cca2: 'GW', flags: { svg: 'https://flagcdn.com/gw.svg', png: 'https://flagcdn.com/w40/gw.png' } },
  { name: { common: "Guyana" }, cca2: 'GY', flags: { svg: 'https://flagcdn.com/gy.svg', png: 'https://flagcdn.com/w40/gy.png' } },
  { name: { common: "Haiti" }, cca2: 'HT', flags: { svg: 'https://flagcdn.com/ht.svg', png: 'https://flagcdn.com/w40/ht.png' } },
  { name: { common: "Heard Island and McDonald Islands" }, cca2: 'HM', flags: { svg: 'https://flagcdn.com/hm.svg', png: 'https://flagcdn.com/w40/hm.png' } },
  { name: { common: "Honduras" }, cca2: 'HN', flags: { svg: 'https://flagcdn.com/hn.svg', png: 'https://flagcdn.com/w40/hn.png' } },
  { name: { common: "Hong Kong" }, cca2: 'HK', flags: { svg: 'https://flagcdn.com/hk.svg', png: 'https://flagcdn.com/w40/hk.png' } },
  { name: { common: "Hungary" }, cca2: 'HU', flags: { svg: 'https://flagcdn.com/hu.svg', png: 'https://flagcdn.com/w40/hu.png' } },
  { name: { common: "Iceland" }, cca2: 'IS', flags: { svg: 'https://flagcdn.com/is.svg', png: 'https://flagcdn.com/w40/is.png' } },
  { name: { common: "India" }, cca2: 'IN', flags: { svg: 'https://flagcdn.com/in.svg', png: 'https://flagcdn.com/w40/in.png' } },
  { name: { common: "Indonesia" }, cca2: 'ID', flags: { svg: 'https://flagcdn.com/id.svg', png: 'https://flagcdn.com/w40/id.png' } },
  { name: { common: "Iran" }, cca2: 'IR', flags: { svg: 'https://flagcdn.com/ir.svg', png: 'https://flagcdn.com/w40/ir.png' } },
  { name: { common: "Iraq" }, cca2: 'IQ', flags: { svg: 'https://flagcdn.com/iq.svg', png: 'https://flagcdn.com/w40/iq.png' } },
  { name: { common: "Ireland" }, cca2: 'IE', flags: { svg: 'https://flagcdn.com/ie.svg', png: 'https://flagcdn.com/w40/ie.png' } },
  { name: { common: "Isle of Man" }, cca2: 'IM', flags: { svg: 'https://flagcdn.com/im.svg', png: 'https://flagcdn.com/w40/im.png' } },
  { name: { common: "Israel" }, cca2: 'IL', flags: { svg: 'https://flagcdn.com/il.svg', png: 'https://flagcdn.com/w40/il.png' } },
  { name: { common: "Italy" }, cca2: 'IT', flags: { svg: 'https://flagcdn.com/it.svg', png: 'https://flagcdn.com/w40/it.png' } },
  { name: { common: "Jamaica" }, cca2: 'JM', flags: { svg: 'https://flagcdn.com/jm.svg', png: 'https://flagcdn.com/w40/jm.png' } },
  { name: { common: "Japan" }, cca2: 'JP', flags: { svg: 'https://flagcdn.com/jp.svg', png: 'https://flagcdn.com/w40/jp.png' } },
  { name: { common: "Jersey" }, cca2: 'JE', flags: { svg: 'https://flagcdn.com/je.svg', png: 'https://flagcdn.com/w40/je.png' } },
  { name: { common: "Jordan" }, cca2: 'JO', flags: { svg: 'https://flagcdn.com/jo.svg', png: 'https://flagcdn.com/w40/jo.png' } },
  { name: { common: "Kazakhstan" }, cca2: 'KZ', flags: { svg: 'https://flagcdn.com/kz.svg', png: 'https://flagcdn.com/w40/kz.png' } },
  { name: { common: "Kenya" }, cca2: 'KE', flags: { svg: 'https://flagcdn.com/ke.svg', png: 'https://flagcdn.com/w40/ke.png' } },
  { name: { common: "Kiribati" }, cca2: 'KI', flags: { svg: 'https://flagcdn.com/ki.svg', png: 'https://flagcdn.com/w40/ki.png' } },
  { name: { common: "Kosovo" }, cca2: 'XK', flags: { svg: 'https://flagcdn.com/xk.svg', png: 'https://flagcdn.com/w40/xk.png' } },
  { name: { common: "Kuwait" }, cca2: 'KW', flags: { svg: 'https://flagcdn.com/kw.svg', png: 'https://flagcdn.com/w40/kw.png' } },
  { name: { common: "Kyrgyzstan" }, cca2: 'KG', flags: { svg: 'https://flagcdn.com/kg.svg', png: 'https://flagcdn.com/w40/kg.png' } },
  { name: { common: "Laos" }, cca2: 'LA', flags: { svg: 'https://flagcdn.com/la.svg', png: 'https://flagcdn.com/w40/la.png' } },
  { name: { common: "Latvia" }, cca2: 'LV', flags: { svg: 'https://flagcdn.com/lv.svg', png: 'https://flagcdn.com/w40/lv.png' } },
  { name: { common: "Lebanon" }, cca2: 'LB', flags: { svg: 'https://flagcdn.com/lb.svg', png: 'https://flagcdn.com/w40/lb.png' } },
  { name: { common: "Lesotho" }, cca2: 'LS', flags: { svg: 'https://flagcdn.com/ls.svg', png: 'https://flagcdn.com/w40/ls.png' } },
  { name: { common: "Liberia" }, cca2: 'LR', flags: { svg: 'https://flagcdn.com/lr.svg', png: 'https://flagcdn.com/w40/lr.png' } },
  { name: { common: "Libya" }, cca2: 'LY', flags: { svg: 'https://flagcdn.com/ly.svg', png: 'https://flagcdn.com/w40/ly.png' } },
  { name: { common: "Liechtenstein" }, cca2: 'LI', flags: { svg: 'https://flagcdn.com/li.svg', png: 'https://flagcdn.com/w40/li.png' } },
  { name: { common: "Lithuania" }, cca2: 'LT', flags: { svg: 'https://flagcdn.com/lt.svg', png: 'https://flagcdn.com/w40/lt.png' } },
  { name: { common: "Luxembourg" }, cca2: 'LU', flags: { svg: 'https://flagcdn.com/lu.svg', png: 'https://flagcdn.com/w40/lu.png' } },
  { name: { common: "Macau" }, cca2: 'MO', flags: { svg: 'https://flagcdn.com/mo.svg', png: 'https://flagcdn.com/w40/mo.png' } },
  { name: { common: "Madagascar" }, cca2: 'MG', flags: { svg: 'https://flagcdn.com/mg.svg', png: 'https://flagcdn.com/w40/mg.png' } },
  { name: { common: "Malawi" }, cca2: 'MW', flags: { svg: 'https://flagcdn.com/mw.svg', png: 'https://flagcdn.com/w40/mw.png' } },
  { name: { common: "Malaysia" }, cca2: 'MY', flags: { svg: 'https://flagcdn.com/my.svg', png: 'https://flagcdn.com/w40/my.png' } },
  { name: { common: "Maldives" }, cca2: 'MV', flags: { svg: 'https://flagcdn.com/mv.svg', png: 'https://flagcdn.com/w40/mv.png' } },
  { name: { common: "Mali" }, cca2: 'ML', flags: { svg: 'https://flagcdn.com/ml.svg', png: 'https://flagcdn.com/w40/ml.png' } },
  { name: { common: "Malta" }, cca2: 'MT', flags: { svg: 'https://flagcdn.com/mt.svg', png: 'https://flagcdn.com/w40/mt.png' } },
  { name: { common: "Marshall Islands" }, cca2: 'MH', flags: { svg: 'https://flagcdn.com/mh.svg', png: 'https://flagcdn.com/w40/mh.png' } },
  { name: { common: "Martinique" }, cca2: 'MQ', flags: { svg: 'https://flagcdn.com/mq.svg', png: 'https://flagcdn.com/w40/mq.png' } },
  { name: { common: "Mauritania" }, cca2: 'MR', flags: { svg: 'https://flagcdn.com/mr.svg', png: 'https://flagcdn.com/w40/mr.png' } },
  { name: { common: "Mauritius" }, cca2: 'MU', flags: { svg: 'https://flagcdn.com/mu.svg', png: 'https://flagcdn.com/w40/mu.png' } },
  { name: { common: "Mayotte" }, cca2: 'YT', flags: { svg: 'https://flagcdn.com/yt.svg', png: 'https://flagcdn.com/w40/yt.png' } },
  { name: { common: "Mexico" }, cca2: 'MX', flags: { svg: 'https://flagcdn.com/mx.svg', png: 'https://flagcdn.com/w40/mx.png' } },
  { name: { common: "Micronesia" }, cca2: 'FM', flags: { svg: 'https://flagcdn.com/fm.svg', png: 'https://flagcdn.com/w40/fm.png' } },
  { name: { common: "Moldova" }, cca2: 'MD', flags: { svg: 'https://flagcdn.com/md.svg', png: 'https://flagcdn.com/w40/md.png' } },
  { name: { common: "Monaco" }, cca2: 'MC', flags: { svg: 'https://flagcdn.com/mc.svg', png: 'https://flagcdn.com/w40/mc.png' } },
  { name: { common: "Mongolia" }, cca2: 'MN', flags: { svg: 'https://flagcdn.com/mn.svg', png: 'https://flagcdn.com/w40/mn.png' } },
  { name: { common: "Montenegro" }, cca2: 'ME', flags: { svg: 'https://flagcdn.com/me.svg', png: 'https://flagcdn.com/w40/me.png' } },
  { name: { common: "Montserrat" }, cca2: 'MS', flags: { svg: 'https://flagcdn.com/ms.svg', png: 'https://flagcdn.com/w40/ms.png' } },
  { name: { common: "Morocco" }, cca2: 'MA', flags: { svg: 'https://flagcdn.com/ma.svg', png: 'https://flagcdn.com/w40/ma.png' } },
  { name: { common: "Mozambique" }, cca2: 'MZ', flags: { svg: 'https://flagcdn.com/mz.svg', png: 'https://flagcdn.com/w40/mz.png' } },
  { name: { common: "Myanmar" }, cca2: 'MM', flags: { svg: 'https://flagcdn.com/mm.svg', png: 'https://flagcdn.com/w40/mm.png' } },
  { name: { common: "Namibia" }, cca2: 'NA', flags: { svg: 'https://flagcdn.com/na.svg', png: 'https://flagcdn.com/w40/na.png' } },
  { name: { common: "Nauru" }, cca2: 'NR', flags: { svg: 'https://flagcdn.com/nr.svg', png: 'https://flagcdn.com/w40/nr.png' } },
  { name: { common: "Nepal" }, cca2: 'NP', flags: { svg: 'https://flagcdn.com/np.svg', png: 'https://flagcdn.com/w40/np.png' } },
  { name: { common: "Netherlands" }, cca2: 'NL', flags: { svg: 'https://flagcdn.com/nl.svg', png: 'https://flagcdn.com/w40/nl.png' } },
  { name: { common: "New Caledonia" }, cca2: 'NC', flags: { svg: 'https://flagcdn.com/nc.svg', png: 'https://flagcdn.com/w40/nc.png' } },
  { name: { common: "New Zealand" }, cca2: 'NZ', flags: { svg: 'https://flagcdn.com/nz.svg', png: 'https://flagcdn.com/w40/nz.png' } },
  { name: { common: "Nicaragua" }, cca2: 'NI', flags: { svg: 'https://flagcdn.com/ni.svg', png: 'https://flagcdn.com/w40/ni.png' } },
  { name: { common: "Niger" }, cca2: 'NE', flags: { svg: 'https://flagcdn.com/ne.svg', png: 'https://flagcdn.com/w40/ne.png' } },
  { name: { common: "Nigeria" }, cca2: 'NG', flags: { svg: 'https://flagcdn.com/ng.svg', png: 'https://flagcdn.com/w40/ng.png' } },
  { name: { common: "Niue" }, cca2: 'NU', flags: { svg: 'https://flagcdn.com/nu.svg', png: 'https://flagcdn.com/w40/nu.png' } },
  { name: { common: "Norfolk Island" }, cca2: 'NF', flags: { svg: 'https://flagcdn.com/nf.svg', png: 'https://flagcdn.com/w40/nf.png' } },
  { name: { common: "North Korea" }, cca2: 'KP', flags: { svg: 'https://flagcdn.com/kp.svg', png: 'https://flagcdn.com/w40/kp.png' } },
  { name: { common: "North Macedonia" }, cca2: 'MK', flags: { svg: 'https://flagcdn.com/mk.svg', png: 'https://flagcdn.com/w40/mk.png' } },
  { name: { common: "Northern Mariana Islands" }, cca2: 'MP', flags: { svg: 'https://flagcdn.com/mp.svg', png: 'https://flagcdn.com/w40/mp.png' } },
  { name: { common: "Norway" }, cca2: 'NO', flags: { svg: 'https://flagcdn.com/no.svg', png: 'https://flagcdn.com/w40/no.png' } },
  { name: { common: "Oman" }, cca2: 'OM', flags: { svg: 'https://flagcdn.com/om.svg', png: 'https://flagcdn.com/w40/om.png' } },
  { name: { common: "Pakistan" }, cca2: 'PK', flags: { svg: 'https://flagcdn.com/pk.svg', png: 'https://flagcdn.com/w40/pk.png' } },
  { name: { common: "Palau" }, cca2: 'PW', flags: { svg: 'https://flagcdn.com/pw.svg', png: 'https://flagcdn.com/w40/pw.png' } },
  { name: { common: "Palestine" }, cca2: 'PS', flags: { svg: 'https://flagcdn.com/ps.svg', png: 'https://flagcdn.com/w40/ps.png' } },
  { name: { common: "Panama" }, cca2: 'PA', flags: { svg: 'https://flagcdn.com/pa.svg', png: 'https://flagcdn.com/w40/pa.png' } },
  { name: { common: "Papua New Guinea" }, cca2: 'PG', flags: { svg: 'https://flagcdn.com/pg.svg', png: 'https://flagcdn.com/w40/pg.png' } },
  { name: { common: "Paraguay" }, cca2: 'PY', flags: { svg: 'https://flagcdn.com/py.svg', png: 'https://flagcdn.com/w40/py.png' } },
  { name: { common: "Peru" }, cca2: 'PE', flags: { svg: 'https://flagcdn.com/pe.svg', png: 'https://flagcdn.com/w40/pe.png' } },
  { name: { common: "Philippines" }, cca2: 'PH', flags: { svg: 'https://flagcdn.com/ph.svg', png: 'https://flagcdn.com/w40/ph.png' } },
  { name: { common: "Pitcairn Islands" }, cca2: 'PN', flags: { svg: 'https://flagcdn.com/pn.svg', png: 'https://flagcdn.com/w40/pn.png' } },
  { name: { common: "Poland" }, cca2: 'PL', flags: { svg: 'https://flagcdn.com/pl.svg', png: 'https://flagcdn.com/w40/pl.png' } },
  { name: { common: "Portugal" }, cca2: 'PT', flags: { svg: 'https://flagcdn.com/pt.svg', png: 'https://flagcdn.com/w40/pt.png' } },
  { name: { common: "Puerto Rico" }, cca2: 'PR', flags: { svg: 'https://flagcdn.com/pr.svg', png: 'https://flagcdn.com/w40/pr.png' } },
  { name: { common: "Qatar" }, cca2: 'QA', flags: { svg: 'https://flagcdn.com/qa.svg', png: 'https://flagcdn.com/w40/qa.png' } },
  { name: { common: "Republic of the Congo" }, cca2: 'CG', flags: { svg: 'https://flagcdn.com/cg.svg', png: 'https://flagcdn.com/w40/cg.png' } },
  { name: { common: "Réunion" }, cca2: 'RE', flags: { svg: 'https://flagcdn.com/re.svg', png: 'https://flagcdn.com/w40/re.png' } },
  { name: { common: "Romania" }, cca2: 'RO', flags: { svg: 'https://flagcdn.com/ro.svg', png: 'https://flagcdn.com/w40/ro.png' } },
  { name: { common: "Russia" }, cca2: 'RU', flags: { svg: 'https://flagcdn.com/ru.svg', png: 'https://flagcdn.com/w40/ru.png' } },
  { name: { common: "Rwanda" }, cca2: 'RW', flags: { svg: 'https://flagcdn.com/rw.svg', png: 'https://flagcdn.com/w40/rw.png' } },
  { name: { common: "Saint Barthélemy" }, cca2: 'BL', flags: { svg: 'https://flagcdn.com/bl.svg', png: 'https://flagcdn.com/w40/bl.png' } },
  { name: { common: "Saint Helena, Ascension and Tristan da Cunha" }, cca2: 'SH', flags: { svg: 'https://flagcdn.com/sh.svg', png: 'https://flagcdn.com/w40/sh.png' } },
  { name: { common: "Saint Kitts and Nevis" }, cca2: 'KN', flags: { svg: 'https://flagcdn.com/kn.svg', png: 'https://flagcdn.com/w40/kn.png' } },
  { name: { common: "Saint Lucia" }, cca2: 'LC', flags: { svg: 'https://flagcdn.com/lc.svg', png: 'https://flagcdn.com/w40/lc.png' } },
  { name: { common: "Saint Martin" }, cca2: 'MF', flags: { svg: 'https://flagcdn.com/mf.svg', png: 'https://flagcdn.com/w40/mf.png' } },
  { name: { common: "Saint Pierre and Miquelon" }, cca2: 'PM', flags: { svg: 'https://flagcdn.com/pm.svg', png: 'https://flagcdn.com/w40/pm.png' } },
  { name: { common: "Saint Vincent and the Grenadines" }, cca2: 'VC', flags: { svg: 'https://flagcdn.com/vc.svg', png: 'https://flagcdn.com/w40/vc.png' } },
  { name: { common: "Samoa" }, cca2: 'WS', flags: { svg: 'https://flagcdn.com/ws.svg', png: 'https://flagcdn.com/w40/ws.png' } },
  { name: { common: "San Marino" }, cca2: 'SM', flags: { svg: 'https://flagcdn.com/sm.svg', png: 'https://flagcdn.com/w40/sm.png' } },
  { name: { common: "São Tomé and Príncipe" }, cca2: 'ST', flags: { svg: 'https://flagcdn.com/st.svg', png: 'https://flagcdn.com/w40/st.png' } },
  { name: { common: "Saudi Arabia" }, cca2: 'SA', flags: { svg: 'https://flagcdn.com/sa.svg', png: 'https://flagcdn.com/w40/sa.png' } },
  { name: { common: "Senegal" }, cca2: 'SN', flags: { svg: 'https://flagcdn.com/sn.svg', png: 'https://flagcdn.com/w40/sn.png' } },
  { name: { common: "Serbia" }, cca2: 'RS', flags: { svg: 'https://flagcdn.com/rs.svg', png: 'https://flagcdn.com/w40/rs.png' } },
  { name: { common: "Seychelles" }, cca2: 'SC', flags: { svg: 'https://flagcdn.com/sc.svg', png: 'https://flagcdn.com/w40/sc.png' } },
  { name: { common: "Sierra Leone" }, cca2: 'SL', flags: { svg: 'https://flagcdn.com/sl.svg', png: 'https://flagcdn.com/w40/sl.png' } },
  { name: { common: "Singapore" }, cca2: 'SG', flags: { svg: 'https://flagcdn.com/sg.svg', png: 'https://flagcdn.com/w40/sg.png' } },
  { name: { common: "Sint Maarten" }, cca2: 'SX', flags: { svg: 'https://flagcdn.com/sx.svg', png: 'https://flagcdn.com/w40/sx.png' } },
  { name: { common: "Slovakia" }, cca2: 'SK', flags: { svg: 'https://flagcdn.com/sk.svg', png: 'https://flagcdn.com/w40/sk.png' } },
  { name: { common: "Slovenia" }, cca2: 'SI', flags: { svg: 'https://flagcdn.com/si.svg', png: 'https://flagcdn.com/w40/si.png' } },
  { name: { common: "Solomon Islands" }, cca2: 'SB', flags: { svg: 'https://flagcdn.com/sb.svg', png: 'https://flagcdn.com/w40/sb.png' } },
  { name: { common: "Somalia" }, cca2: 'SO', flags: { svg: 'https://flagcdn.com/so.svg', png: 'https://flagcdn.com/w40/so.png' } },
  { name: { common: "South Africa" }, cca2: 'ZA', flags: { svg: 'https://flagcdn.com/za.svg', png: 'https://flagcdn.com/w40/za.png' } },
  { name: { common: "South Georgia" }, cca2: 'GS', flags: { svg: 'https://flagcdn.com/gs.svg', png: 'https://flagcdn.com/w40/gs.png' } },
  { name: { common: "South Korea" }, cca2: 'KR', flags: { svg: 'https://flagcdn.com/kr.svg', png: 'https://flagcdn.com/w40/kr.png' } },
  { name: { common: "South Sudan" }, cca2: 'SS', flags: { svg: 'https://flagcdn.com/ss.svg', png: 'https://flagcdn.com/w40/ss.png' } },
  { name: { common: "Spain" }, cca2: 'ES', flags: { svg: 'https://flagcdn.com/es.svg', png: 'https://flagcdn.com/w40/es.png' } },
  { name: { common: "Sri Lanka" }, cca2: 'LK', flags: { svg: 'https://flagcdn.com/lk.svg', png: 'https://flagcdn.com/w40/lk.png' } },
  { name: { common: "Sudan" }, cca2: 'SD', flags: { svg: 'https://flagcdn.com/sd.svg', png: 'https://flagcdn.com/w40/sd.png' } },
  { name: { common: "Suriname" }, cca2: 'SR', flags: { svg: 'https://flagcdn.com/sr.svg', png: 'https://flagcdn.com/w40/sr.png' } },
  { name: { common: "Svalbard and Jan Mayen" }, cca2: 'SJ', flags: { svg: 'https://flagcdn.com/sj.svg', png: 'https://flagcdn.com/w40/sj.png' } },
  { name: { common: "Sweden" }, cca2: 'SE', flags: { svg: 'https://flagcdn.com/se.svg', png: 'https://flagcdn.com/w40/se.png' } },
  { name: { common: "Switzerland" }, cca2: 'CH', flags: { svg: 'https://flagcdn.com/ch.svg', png: 'https://flagcdn.com/w40/ch.png' } },
  { name: { common: "Syria" }, cca2: 'SY', flags: { svg: 'https://flagcdn.com/sy.svg', png: 'https://flagcdn.com/w40/sy.png' } },
  { name: { common: "Taiwan" }, cca2: 'TW', flags: { svg: 'https://flagcdn.com/tw.svg', png: 'https://flagcdn.com/w40/tw.png' } },
  { name: { common: "Tajikistan" }, cca2: 'TJ', flags: { svg: 'https://flagcdn.com/tj.svg', png: 'https://flagcdn.com/w40/tj.png' } },
  { name: { common: "Tanzania" }, cca2: 'TZ', flags: { svg: 'https://flagcdn.com/tz.svg', png: 'https://flagcdn.com/w40/tz.png' } },
  { name: { common: "Thailand" }, cca2: 'TH', flags: { svg: 'https://flagcdn.com/th.svg', png: 'https://flagcdn.com/w40/th.png' } },
  { name: { common: "Timor-Leste" }, cca2: 'TL', flags: { svg: 'https://flagcdn.com/tl.svg', png: 'https://flagcdn.com/w40/tl.png' } },
  { name: { common: "Togo" }, cca2: 'TG', flags: { svg: 'https://flagcdn.com/tg.svg', png: 'https://flagcdn.com/w40/tg.png' } },
  { name: { common: "Tokelau" }, cca2: 'TK', flags: { svg: 'https://flagcdn.com/tk.svg', png: 'https://flagcdn.com/w40/tk.png' } },
  { name: { common: "Tonga" }, cca2: 'TO', flags: { svg: 'https://flagcdn.com/to.svg', png: 'https://flagcdn.com/w40/to.png' } },
  { name: { common: "Trinidad and Tobago" }, cca2: 'TT', flags: { svg: 'https://flagcdn.com/tt.svg', png: 'https://flagcdn.com/w40/tt.png' } },
  { name: { common: "Tunisia" }, cca2: 'TN', flags: { svg: 'https://flagcdn.com/tn.svg', png: 'https://flagcdn.com/w40/tn.png' } },
  { name: { common: "Turkey" }, cca2: 'TR', flags: { svg: 'https://flagcdn.com/tr.svg', png: 'https://flagcdn.com/w40/tr.png' } },
  { name: { common: "Turkmenistan" }, cca2: 'TM', flags: { svg: 'https://flagcdn.com/tm.svg', png: 'https://flagcdn.com/w40/tm.png' } },
  { name: { common: "Turks and Caicos Islands" }, cca2: 'TC', flags: { svg: 'https://flagcdn.com/tc.svg', png: 'https://flagcdn.com/w40/tc.png' } },
  { name: { common: "Tuvalu" }, cca2: 'TV', flags: { svg: 'https://flagcdn.com/tv.svg', png: 'https://flagcdn.com/w40/tv.png' } },
  { name: { common: "Uganda" }, cca2: 'UG', flags: { svg: 'https://flagcdn.com/ug.svg', png: 'https://flagcdn.com/w40/ug.png' } },
  { name: { common: "Ukraine" }, cca2: 'UA', flags: { svg: 'https://flagcdn.com/ua.svg', png: 'https://flagcdn.com/w40/ua.png' } },
  { name: { common: "United Arab Emirates" }, cca2: 'AE', flags: { svg: 'https://flagcdn.com/ae.svg', png: 'https://flagcdn.com/w40/ae.png' } },
  { name: { common: "United Kingdom" }, cca2: 'GB', flags: { svg: 'https://flagcdn.com/gb.svg', png: 'https://flagcdn.com/w40/gb.png' } },
  { name: { common: "United Nations" }, cca2: 'UN', flags: { svg: 'https://flagcdn.com/un.svg', png: 'https://flagcdn.com/w40/un.png' } },
  { name: { common: "United States" }, cca2: 'US', flags: { svg: 'https://flagcdn.com/us.svg', png: 'https://flagcdn.com/w40/us.png' } },
  { name: { common: "United States Minor Outlying Islands" }, cca2: 'UM', flags: { svg: 'https://flagcdn.com/um.svg', png: 'https://flagcdn.com/w40/um.png' } },
  { name: { common: "United States Virgin Islands" }, cca2: 'VI', flags: { svg: 'https://flagcdn.com/vi.svg', png: 'https://flagcdn.com/w40/vi.png' } },
  { name: { common: "Uruguay" }, cca2: 'UY', flags: { svg: 'https://flagcdn.com/uy.svg', png: 'https://flagcdn.com/w40/uy.png' } },
  { name: { common: "Uzbekistan" }, cca2: 'UZ', flags: { svg: 'https://flagcdn.com/uz.svg', png: 'https://flagcdn.com/w40/uz.png' } },
  { name: { common: "Vanuatu" }, cca2: 'VU', flags: { svg: 'https://flagcdn.com/vu.svg', png: 'https://flagcdn.com/w40/vu.png' } },
  { name: { common: "Vatican City (Holy See)" }, cca2: 'VA', flags: { svg: 'https://flagcdn.com/va.svg', png: 'https://flagcdn.com/w40/va.png' } },
  { name: { common: "Venezuela" }, cca2: 'VE', flags: { svg: 'https://flagcdn.com/ve.svg', png: 'https://flagcdn.com/w40/ve.png' } },
  { name: { common: "Vietnam" }, cca2: 'VN', flags: { svg: 'https://flagcdn.com/vn.svg', png: 'https://flagcdn.com/w40/vn.png' } },
  { name: { common: "Wallis and Futuna" }, cca2: 'WF', flags: { svg: 'https://flagcdn.com/wf.svg', png: 'https://flagcdn.com/w40/wf.png' } },
  { name: { common: "Western Sahara" }, cca2: 'EH', flags: { svg: 'https://flagcdn.com/eh.svg', png: 'https://flagcdn.com/w40/eh.png' } },
  { name: { common: "Yemen" }, cca2: 'YE', flags: { svg: 'https://flagcdn.com/ye.svg', png: 'https://flagcdn.com/w40/ye.png' } },
  { name: { common: "Zambia" }, cca2: 'ZM', flags: { svg: 'https://flagcdn.com/zm.svg', png: 'https://flagcdn.com/w40/zm.png' } },
  { name: { common: "Zimbabwe" }, cca2: 'ZW', flags: { svg: 'https://flagcdn.com/zw.svg', png: 'https://flagcdn.com/w40/zw.png' } },
]
